<?php
$timezones = array (
"إفريقيا / أبيدجان",
"إفريقيا / أكرا",
"إفريقيا / أديس أبابا",
"إفريقيا / الجزائر",
"إفريقيا / أسمرة",
"إفريقيا / أسمرة",
"إفريقيا / باماكو",
"إفريقيا / بانغي",
"إفريقيا / بانجول",
"إفريقيا / بيساو",
"إفريقيا / بلانتير",
"إفريقيا / برازافيل",
"إفريقيا / بوجومبورا",
"إفريقيا / القاهرة",
"إفريقيا / الدار البيضاء",
"إفريقيا / سبتة",
"إفريقيا / كوناكري",
"إفريقيا / داكار",
"إفريقيا / دار السلام",
"إفريقيا / جيبوتي",
"إفريقيا / دوالا",
"إفريقيا / العيون",
"إفريقيا / فريتاون",
"إفريقيا / جابورون",
"إفريقيا / هراري",
"إفريقيا / جوهانسبرغ",
"إفريقيا / جوبا",
"إفريقيا / كمبالا",
"إفريقيا / الخرطوم",
"إفريقيا / كيغالي",
"إفريقيا / كينشاسا",
"إفريقيا / لاغوس",
"إفريقيا / ليبرفيل",
"إفريقيا / لومي",
"إفريقيا / لواندا",
"إفريقيا / لوبومباشي",
"إفريقيا / لوساكا",
"إفريقيا / مالابو",
"إفريقيا / مابوتو",
"إفريقيا / ماسيرو",
"إفريقيا / مبابان",
"إفريقيا / مقديشو",
"إفريقيا / مونروفيا",
"إفريقيا / نيروبي",
"إفريقيا / نجامينا",
"إفريقيا / نيامي",
"إفريقيا / نواكشوط",
"إفريقيا / واغادوغو",
"إفريقيا / بورتو نوفو",
"إفريقيا / ساو تومي",
"إفريقيا / تمبكتو",
"إفريقيا / طرابلس",
"إفريقيا / تونس",
"إفريقيا / ويندهوك",
"أمريكا / Adak",
"أمريكا / مرسى",
"أمريكا / أنغيلا",
"أمريك ا/ أنتيجوا",
"أمريكا / أراغوينا",
"أمريكا / الأرجنتين  / Buenos_Aires",
"أمريكا / الأرجنتين  / كاتاماركا",
"أمريكا / الأرجنتين  / كومودريفادافيا",
"أمريكا / الأرجنتين  / قرطبة",
"أمريكا / الأرجنتين  / خوخوي",
"أمريكا / الأرجنتين  / La_Rioja",
"أمريكا / الأرجنتين  / مندوزا",
"أمريكا / الأرجنتين  / Rio_Gallegos",
"أمريكا / الأرجنتين  / سالتا",
"أمريكا / الأرجنتين  / San_Juan",
"أمريكا / الأرجنتين  / San_Luis",
"أمريكا / الأرجنتين  / توكومان",
"أمريكا / الأرجنتين  / أوشوايا",
"أمريكا / أروبا",
"أمريكا / أسونسيون",
"أمريكا / Atikokan",
"أمريكا / أتكا",
"أمريكا / باهيا",
"أمريكا / Bahia_Banderas",
"أمريكا / بربادوس",
"أمريكا / بيليم",
"أمريكا / بليز",
"أمريكا / بلان سابلون",
"أمريكا / Boa_Vista",
"أمريكا / بوغوتا",
"أمريكا / Boise",
"أمريكا / Buenos_Aires",
"أمريكا / Cambridge_Bay",
"أمريكا / Campo_Grande",
"أمريكا / Cancun",
"أمريكا / Caracas",
"أمريكا / Catamarca",
"أمريكا/ Cayenne",
"أمريكا/ Cayman",
"أمريكا/ Chicago",
"أمريكا/ Chihuahua",
"أمريكا/ Coral_Harbour",
"أمريكا/ Cordoba",
"أمريكا/ Costa_Rica",
"أمريكا/ Creston",
"أمريكا/ Cuiaba",
"أمريكا/ Curacao",
"أمريكا/ Danmarkshavn",
"أمريكا/ Dawson",
"أمريكا/ Dawson_Creek",
"أمريكا/ Denver",
"أمريكا/ Detroit",
"أمريكا/ Dominica",
"أمريكا/ Edmonton",
"أمريكا/ Eirunepe",
"أمريكا/ El_Salvador",
"أمريكا/ Ensenada",
"أمريكا/ Fort_Wayne",
"أمريكا/ Fortaleza",
"أمريكا/ Glace_Bay",
"أمريكا/ Godthab",
"أمريكا/ Goose_Bay",
"أمريكا/ Grand_Turk",
"أمريكا/ Grenada",
"أمريكا/ Guadeloupe",
"أمريكا/ Guatemala",
"أمريكا/ Guayaquil",
"أمريكا/ Guyana",
"أمريكا/ Halifax",
"أمريكا/ Havana",
"أمريكا/ Hermosillo",
"أمريكا/ Indiana/Indianapolis",
"أمريكا/ Indiana/Knox",
"أمريكا/ Indiana/Marengo",
"أمريكا/ Indiana/Petersburg",
"أمريكا/ Indiana/Tell_City",
"أمريكا/ Indiana/Vevay",
"أمريكا/ Indiana/Vincennes",
"أمريكا/ Indiana/Winamac",
"أمريكا/ Indianapolis",
"أمريكا/ Inuvik",
"أمريكا/ Iqaluit",
"أمريكا/ Jamaica",
"أمريكا/ Jujuy",
"أمريكا/ Juneau",
"أمريكا/ Kentucky/Louisville",
"أمريكا/ Kentucky/Monticello",
"أمريكا/ Knox_IN",
"أمريكا/ Kralendijk",
"أمريكا/ La_Paz",
"أمريكا/ Lima",
"أمريكا/ Los_Angeles",
"أمريكا/ Louisville",
"أمريكا/ Lower_Princes",
"أمريكا/ Maceio",
"أمريكا/ Managua",
"أمريكا/ Manaus",
"أمريكا/ Marigot",
"أمريكا/ Martinique",
"أمريكا/ Matamoros",
"أمريكا/ Mazatlan",
"أمريكا/ Mendoza",
"أمريكا/ Menominee",
"أمريكا/ Merida",
"أمريكا/ Metlakatla",
"أمريكا/ Mexico_City",
"أمريكا/ Miquelon",
"أمريكا/ Moncton",
"أمريكا/ Monterrey",
"أمريكا/ Montevideo",
"أمريكا/ Montreal",
"أمريكا/ Montserrat",
"أمريكا/ Nassau",
"أمريكا/ New_York",
"أمريكا/ Nipigon",
"أمريكا/ Nome",
"أمريكا/ Noronha",
"أمريكا/ North_Dakota/Beulah",
"أمريكا/ North_Dakota/Center",
"أمريكا/ North_Dakota/New_Salem",
"أمريكا/ Ojinaga",
"أمريكا/ Panama",
"أمريكا/ Pangnirtung",
"أمريكا/ Paramaribo",
"أمريكا/ Phoenix",
"أمريكا/ Port-au-Prince",
"أمريكا/ Port_of_Spain",
"أمريكا/ Porto_Acre",
"أمريكا/ Porto_Velho",
"أمريكا/ Puerto_Rico",
"أمريكا/ Rainy_River",
"أمريكا/ Rankin_Inlet",
"أمريكا/ Recife",
"أمريكا/ Regina",
"أمريكا/ Resolute",
"أمريكا/ Rio_Branco",
"أمريكا/ Rosario",
"أمريكا/ Santa_Isabel",
"أمريكا/ Santarem",
"أمريكا/ Santiago",
"أمريكا/ Santo_Domingo",
"أمريكا/ Sao_Paulo",
"أمريكا/ Scoresbysund",
"أمريكا/ Shiprock",
"أمريكا/ Sitka",
"أمريكا/ St_Barthelemy",
"أمريكا/ St_Johns",
"أمريكا/ St_Kitts",
"أمريكا/ St_Lucia",
"أمريكا/ St_Thomas",
"أمريكا/ St_Vincent",
"أمريكا/ Swift_Current",
"أمريكا/ Tegucigalpa",
"أمريكا/ Thule",
"أمريكا/ Thunder_Bay",
"أمريكا/ Tijuana",
"أمريكا/ Toronto",
"أمريكا/ Tortola",
"أمريكا/ Vancouver",
"أمريكا/ Virgin",
"أمريكا/ Whitehorse",
"أمريكا/ Winnipeg",
"أمريكا/ Yakutat",
"أمريكا/ Yellowknife",
"أنتاركتيكا /Casey",
"أنتاركتيكا /Davis",
"أنتاركتيكا /DumontDUrville",
"أنتاركتيكا /Macquarie",
"أنتاركتيكا /Mawson",
"أنتاركتيكا /McMurdo",
"أنتاركتيكا /Palmer",
"أنتاركتيكا /Rothera",
"أنتاركتيكا /South_Pole",
"أنتاركتيكا /Syowa",
"أنتاركتيكا /Troll",
"أنتاركتيكا /Vostok",
"القطب الشمالي / لونجييربين",
"آسيا / Aden",
"آسيا / Almaty",
"آسيا / Amman",
"آسيا / Anadyr",
"آسيا / Aqtau",
"آسيا / Aqtobe",
"آسيا / Ashgabat",
"آسيا / Ashkhabad",
"آسيا / Baghdad",
"آسيا / Bahrain",
"آسيا / Baku",
"آسيا / Bangkok",
"آسيا / Beirut",
"آسيا / Bishkek",
"آسيا / Brunei",
"آسيا / Calcutta",
"آسيا / Chita",
"آسيا / Choibalsan",
"آسيا / Chongqing",
"آسيا / Chungking",
"آسيا / Colombo",
"آسيا / Dacca",
"آسيا / Damascus",
"آسيا / Dhaka",
"آسيا / Dili",
"آسيا / Dubai",
"آسيا / Dushanbe",
"آسيا / Gaza",
"آسيا / Hanoi",
"آسيا / Harbin",
"آسيا / Hebron",
"آسيا / Ho_Chi_Minh",
"آسيا / Hong_Kong",
"آسيا / Hovd",
"آسيا / Irkutsk",
"آسيا / Istanbul",
"آسيا / Jakarta",
"آسيا / Jayapura",
"آسيا / Jerusalem",
"آسيا / Kabul",
"آسيا / Kamchatka",
"آسيا / Karachi",
"آسيا / Kashgar",
"آسيا / Kathmandu",
"آسيا / Katmandu",
"آسيا / Khandyga",
"آسيا / Kolkata",
"آسيا / Krasnoyarsk",
"آسيا / Kuala_Lumpur",
"آسيا / Kuching",
"آسيا / Kuwait",
"آسيا / Macao",
"آسيا / Macau",
"آسيا / Magadan",
"آسيا / Makassar",
"آسيا / Manila",
"آسيا / Muscat",
"آسيا / Nicosia",
"آسيا / Novokuznetsk",
"آسيا / Novosibirsk",
"آسيا / Omsk",
"آسيا / Oral",
"آسيا / Phnom_Penh",
"آسيا / Pontianak",
"آسيا / Pyongyang",
"آسيا / Qatar",
"آسيا / Qyzylorda",
"آسيا / Rangoon",
"آسيا / Riyadh",
"آسيا / Saigon",
"آسيا / Sakhalin",
"آسيا / Samarkand",
"آسيا / Seoul",
"آسيا / Shanghai",
"آسيا / Singapore",
"آسيا / Srednekolymsk",
"آسيا / Taipei",
"آسيا / Tashkent",
"آسيا / Tbilisi",
"آسيا / Tehran",
"آسيا / Tel_Aviv",
"آسيا / Thimbu",
"آسيا / Thimphu",
"آسيا / Tokyo",
"آسيا / Ujung_Pandang",
"آسيا / Ulaanbaatar",
"آسيا / Ulan_Bator",
"آسيا / Urumqi",
"آسيا / Ust-Nera",
"آسيا / Vientiane",
"آسيا / Vladivostok",
"آسيا / Yakutsk",
"آسيا / Yekaterinburg",
"آسيا / Yerevan",
"الأطلنطي  / Azores",
"الأطلنطي  / Bermuda",
"الأطلنطي  / Canary",
"الأطلنطي  / Cape_Verde",
"الأطلنطي  / Faeroe",
"الأطلنطي  / Faroe",
"الأطلنطي  / Jan_Mayen",
"الأطلنطي  / Madeira",
"الأطلنطي  / Reykjavik",
"الأطلنطي  / South_Georgia",
"الأطلنطي  / St_Helena",
"الأطلنطي  / Stanley",
"أستراليا  / ACT",
"أستراليا  / Adelaide",
"أستراليا  / Brisbane",
"أستراليا  / Broken_Hill",
"أستراليا  / Canberra",
"أستراليا  / Currie",
"أستراليا  / Darwin",
"أستراليا  / Eucla",
"أستراليا  / Hobart",
"أستراليا  / LHI",
"أستراليا  / Lindeman",
"أستراليا  / Lord_Howe",
"أستراليا  / Melbourne",
"أستراليا  / NSW",
"أستراليا  / North",
"أستراليا  / Perth",
"أستراليا  / Queensland",
"أستراليا  / South",
"أستراليا  / Sydney",
"أستراليا  / Tasmania",
"أستراليا  / Victoria",
"أستراليا  / West",
"أستراليا  / Yancowinna",
"البرازيل  / Acre",
"البرازيل  / DeNoronha",
"البرازيل  / East",
"البرازيل  / West",
"CET",
"CST6CDT",
"كندا / Atlantic",
"كندا / Central",
"كندا / East-Saskatchewan",
"كندا / Eastern",
"كندا / Mountain",
"كندا / Newfoundland",
"كندا / Pacific",
"كندا / Saskatchewan",
"كندا / Yukon",
"شيلي  / Continental",
"شيلي  / EasterIsland",
"Cuba",
"EET",
"EST",
"EST5EDT",
"Egypt",
"Eire",
"إلخ / GMT",
"إلخ / GMT+0",
"إلخ / GMT+1",
"إلخ / GMT+10",
"إلخ / GMT+11",
"إلخ / GMT+12",
"إلخ / GMT+2",
"إلخ / GMT+3",
"إلخ / GMT+4",
"إلخ / GMT+5",
"إلخ / GMT+6",
"إلخ / GMT+7",
"إلخ / GMT+8",
"إلخ / GMT+9",
"إلخ / GMT-0",
"إلخ / GMT-1",
"إلخ / GMT-10",
"إلخ / GMT-11",
"إلخ / GMT-12",
"إلخ / GMT-13",
"إلخ / GMT-14",
"إلخ / GMT-2",
"إلخ / GMT-3",
"إلخ / GMT-4",
"إلخ / GMT-5",
"إلخ / GMT-6",
"إلخ / GMT-7",
"إلخ / GMT-8",
"إلخ / GMT-9",
"إلخ / GMT0",
"إلخ / Greenwich",
"إلخ / UCT",
"إلخ / UTC",
"إلخ / Universal",
"إلخ / Zulu",
"أوروبا  / Amsterdam",
"أوروبا  / Andorra",
"أوروبا  / Athens",
"أوروبا  / Belfast",
"أوروبا  / Belgrade",
"أوروبا  / Berlin",
"أوروبا  / Bratislava",
"أوروبا  / Brussels",
"أوروبا  / Bucharest",
"أوروبا  / Budapest",
"أوروبا  / Busingen",
"أوروبا  / Chisinau",
"أوروبا  / Copenhagen",
"أوروبا  / Dublin",
"أوروبا  / Gibraltar",
"أوروبا  / Guernsey",
"أوروبا  / Helsinki",
"أوروبا  / Isle_of_Man",
"أوروبا  / Istanbul",
"أوروبا  / Jersey",
"أوروبا  / Kaliningrad",
"أوروبا  / Kiev",
"أوروبا  / Lisbon",
"أوروبا  / Ljubljana",
"أوروبا  / London",
"أوروبا  / Luxembourg",
"أوروبا  / Madrid",
"أوروبا  / Malta",
"أوروبا  / Mariehamn",
"أوروبا  / Minsk",
"أوروبا  / Monaco",
"أوروبا  / Moscow",
"أوروبا  / Nicosia",
"أوروبا  / Oslo",
"أوروبا  / Paris",
"أوروبا  / Podgorica",
"أوروبا  / Prague",
"أوروبا  / Riga",
"أوروبا  / Rome",
"أوروبا  / Samara",
"أوروبا  / San_Marino",
"أوروبا  / Sarajevo",
"أوروبا  / Simferopol",
"أوروبا  / Skopje",
"أوروبا  / Sofia",
"أوروبا  / Stockholm",
"أوروبا  / Tallinn",
"أوروبا  / Tirane",
"أوروبا  / Tiraspol",
"أوروبا  / Uzhgorod",
"أوروبا  / Vaduz",
"أوروبا  / Vatican",
"أوروبا  / Vienna",
"أوروبا  / Vilnius",
"أوروبا  / Volgograd",
"أوروبا  / Warsaw",
"أوروبا  / Zagreb",
"أوروبا  / Zaporozhye",
"أوروبا  / Zurich",
"غيغابايت",
"GB-Eire",
"GMT",
"GMT+0",
"GMT-0",
"GMT0",
"Greenwich",
"HST",
"Hongkong",
"Iceland",
"Indian/Antananarivo",
"Indian/Chagos",
"Indian/Christmas",
"Indian/Cocos",
"Indian/Comoro",
"Indian/Kerguelen",
"Indian/Mahe",
"Indian/Maldives",
"Indian/Mauritius",
"Indian/Mayotte",
"Indian/Reunion",
"Iran",
"Israel",
"Jamaica",
"Japan",
"Kwajalein",
"Libya",
"MET",
"MST",
"MST7MDT",
"Mexico/BajaNorte",
"Mexico/BajaSur",
"Mexico/General",
"NZ",
"NZ-CHAT",
"Navajo",
"PRC",
"PST8PDT",
"المحيط الهادئ / Apia",
"المحيط الهادئ / Auckland",
"المحيط الهادئ / Bougainville",
"المحيط الهادئ / Chatham",
"المحيط الهادئ / Chuuk",
"المحيط الهادئ / Easter",
"المحيط الهادئ / Efate",
"المحيط الهادئ / Enderbury",
"المحيط الهادئ / Fakaofo",
"المحيط الهادئ / Fiji",
"المحيط الهادئ / Funafuti",
"المحيط الهادئ / Galapagos",
"المحيط الهادئ / Gambier",
"المحيط الهادئ / Guadalcanal",
"المحيط الهادئ / Guam",
"المحيط الهادئ / Honolulu",
"المحيط الهادئ / Johnston",
"المحيط الهادئ / Kiritimati",
"المحيط الهادئ / Kosrae",
"المحيط الهادئ / Kwajalein",
"المحيط الهادئ / Majuro",
"المحيط الهادئ / Marquesas",
"المحيط الهادئ / Midway",
"المحيط الهادئ / Nauru",
"المحيط الهادئ / Niue",
"المحيط الهادئ / Norfolk",
"المحيط الهادئ / Noumea",
"المحيط الهادئ / Pago_Pago",
"المحيط الهادئ / Palau",
"المحيط الهادئ / Pitcairn",
"المحيط الهادئ / Pohnpei",
"المحيط الهادئ / Ponape",
"المحيط الهادئ / Port_Moresby",
"المحيط الهادئ / Rarotonga",
"المحيط الهادئ / Saipan",
"المحيط الهادئ / Samoa",
"المحيط الهادئ / Tahiti",
"المحيط الهادئ / Tarawa",
"المحيط الهادئ / Tongatapu",
"المحيط الهادئ / Truk",
"المحيط الهادئ / Wake",
"المحيط الهادئ / Wallis",
"المحيط الهادئ / Yap",
"Poland",
"Portugal",
"ROC",
"ROK",
"Singapore",
"Turkey",
"UCT",
"US/Alaska",
"US/Aleutian",
"US/Arizona",
"US/Central",
"US/East-Indiana",
"US/Eastern",
"US/Hawaii",
"US/Indiana-Starke",
"US/Michigan",
"US/Mountain",
"US/Pacific",
"US/Samoa",
"UTC",
"Universal",
"W-SU",
"WET",
"Zulu");